### ISSUE TITLE
Kubernetes config?

### ISSUE THREAD

**Issue by aliakhtar** [rawmind0/k8s-kafka#1]
Is this image intended to be used for Kubernetes? If so, can you also add the .yaml or .json spec files for kubernetes, which describe which services / deployments are needed to be created?

**Comment by rawmind0** [comment]
Yep...This image provides dynamic config to kafka, based in kubernetes. 

As you could read at README.md, this has to be deployed in conjuntion alpine-kafka. In alpine-kafka repo, you could see the files that you are requesting, which define the replication controller and the service. https://github.com/rawmind0/alpine-kafka/tree/master/k8s

Think about that this k8s files are for deploy the service thought rancher catalog, but you could adapt them to be deployed in a "pure" k8s environment. 

You need too alpine-zk, to run a zookeeper cluster in k8s, needed by kafka.
https://github.com/rawmind0/alpine-zk

Best regards....

**Comment by aliakhtar** [comment]
@rawmind0 I'm not familiar with Rancher. What will need to be changed to adapt the files for a pure k8 environment?

**Comment by rawmind0** [comment]
@aliakhtar, basically, the value of the variables that are in rc and service yml files. With rancher the value of these variables comes from rancher-catalog.yml

You should change the variables with a concrete values, to deploy in a pure kubernetes. 

These are the variables and the default values....
- kafka_name="kafka"                    # kafka k8s service and rc name.
- kafka_namespace="kafka"               # kafka k8s namespace
- kafka_scale=3                         # kafka scale to deploy.
- kafka_mem=512                         # kafka broker memory.
- kafka_log_dir="/opt/kafka/logs"       # Kafka log dir.
- kafka_log_retention="168"             # kafka log retention. 
- kafka_num_partitions="1"              # Kafka partitions number
- kafka_delete_topics="false"           # kafka delete topics
- kafka_pub_ip= < true | false >        # Advertise public ip to zookeeper.
- zk_link="kafka-zk/zk"                 # zookeeper namespace/service to connect to.

The package, expect that kubernetes etcd would be resolved as etcd.  You could change that setting variable at broker-conf container ${CONF_BACKEND:-"etcd"}

Tell me if you need more help.

Best regards...
